modLoader="kotlinfml"
loaderVersion="[1,)"

[[mods]]
    modId="deepmining"
    version="${file.jarVersion}"
    displayName="Deep Mining"
    displayURL="https://github.com/hnOsmium0001/DeepMining"
    issueTrackerURL="https://github.com/hnOsmium0001/DeepMining/issues"
    authors="hnOsmium0001"
    description='''
    Customizable, factorio style mining system
    '''

[[dependencies.deepmining]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.deepmining]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
